name: Contact_Plus
description: "A simple flutter contact app with crudcrud.com backend using bloc state management by mrxcode."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_slidable: ^3.1.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  getwidget: ^4.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  date_cupertino_bottom_sheet_picker: ^0.0.4
  get: ^4.6.6
  url_launcher: ^6.3.0
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/onboarding/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/logo.png"
    background_color: "#hexcode"
    theme_color: "#1100ff"
  macos:
    generate: true
    image_path: "assets/logos/logo.png"
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
