name: simple_contact_with_crud_backend_using_bloc_state_management_by_mrxcode
description: "A simple flutter contact app with crudcrud.com backend using bloc state management by mrxcode."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_slidable: ^3.1.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  getwidget: ^4.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  date_cupertino_bottom_sheet_picker: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  #assets:
  #  - assets/logos
  #  - assets/onboarding
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
